/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263_hw03;

/**
 * Represents the appliction
 */
public class App {
    /**
     * The application entrypoint
     * @param args The cli args
     */
    public static void main(String[] args) {
        return;
    }
}
