/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263_hw03;


import javafx.application.Application;

/**
 * Represents the appliction
 */
public class App {
    static private CourseProcessor processor;

    /**
     * The application entrypoint
     * @param args The cli args
     */
    public static void main(String[] args) {
        processor = new CourseProcessor();
        Application.launch(processor.getClass(), args);
    }
}
